config/routes.rb
Rails.application.routes.draw do
  get 'csvs/index'
  get 'csvs/new'
  resources :books
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    get '/login' => 'users/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
    get '/users/confirm' => 'registrations#confirm'
    post '/users/invitations' => 'users/invitations#resend'
  end

  root to: 'home#index'

  resources :csvs, only: %i[index new create] do
    resources :books
  end
end

app/views/layouts/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg py-4 navbar-dark bg-primary">
  <div class="container lead">
    <a class="navbar-brand fw-bolder" href="/">Ubiquity Book Explorer</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to 'Past Uploads', csvs_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to 'Edit Profile', edit_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <div class="nav-link disabled fw-bolder">
              Logged in as <strong><%= current_user.full_name %></strong>.
            </div>
          </li>
          <li class="nav-item">
            <%= link_to "Log Out", logout_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link"  %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", login_path, class: "nav-link"  %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/shared/_notice.html.erb
<% if notice %>
  <p class="lead alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="lead alert alert-danger"><%= alert %></p>
<% end %>