config/routes.rb
Rails.application.routes.draw do
  get 'csvs/index'
  get 'csvs/new'
  resources :books
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    get '/login' => 'users/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
    get '/users/confirm' => 'registrations#confirm'
    post '/users/invitations' => 'users/invitations#resend'
  end

  root to: 'home#index'

  resources :csvs, only: %i[index new create] do
    resources :books
  end
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  belongs_to :csv

  attribute :uuid, MySQLBinUUID::Type.new

  UUID_REGEX = /\A[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\z/i

  validates :uuid,  presence: true,
                    format: { with: UUID_REGEX, message: 'Invalid UUID' },
                    uniqueness: { scope: :csv_id, case_sensitive: false }
  validates :title, presence: true
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_csv
  before_action :set_book, only: %i[show edit update destroy]

  # GET /books or /books.json
  def index
    @books = @csv.books
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)
    @book.uuid = SecureRandom.uuid

    respond_to do |format|
      if @book.save
        format.html { redirect_to csv_book_url(@csv, @book), notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to csv_book_url(@csv, @book), notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to csv_books_url(@csv), status: :see_other, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_csv
    @csv = Csv.find(params[:csv_id])
  end

  def set_book
    @book = Book.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def book_params
    params.require(:book).permit(:title, :author, :date_published, :publisher_name)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div class="w-100 mx-auto", id="<%= dom_id book %>">
  <div class="card shadow mt-4 mb-5">
    <div class="card-body">
      <dl class="row">
        <dt class="col-sm-3">Title</dt>
        <dd class="col-sm-9"><%= book.title %></dd>
      </dl>
      <dl class="row">
        <dt class="col-sm-3">Author</dt>
        <dd class="col-sm-9"><%= book.author %></dd>
      </dl>
      <dl class="row">
        <dt class="col-sm-3">Date published</dt>
        <dd class="col-sm-9"><%= book.date_published.strftime('%a, %d %b %Y') %></dd>
      </dl>
      <dl class="row">
        <dt class="col-sm-3">Publisher name</dt>
        <dd class="col-sm-9"><%= book.publisher_name %></dd>
      </dl>
    </div>
  </div>
</div>

app/views/books/_books_table.html.erb
<% if books.present? %>
  <div class="card shadow mt-4 mb-5 mx-auto">
    <div class="card-body">
      <table class="table table-hover">
        <thead class="lead fw-bolder">
        <tr>
          <th scope="col">Book Title</th>
          <th scope="col">Author</th>
          <th scope="col">Date Published</th>
          <th scope="col">Publisher</th>
          <th scope="col"></th>
        </tr>
        </thead>
        <tbody class="lead">
        <% books.each do |book| %>
          <tr>
            <td><%= book.title %></td>
            <td><%= book.author %></td>
            <td><%= book.date_published.strftime('%a, %d %b %Y') %></td>
            <td><%= book.publisher_name %></td>
            <td>
              <%= link_to 'Show', csv_book_path(@csv, book), class:"btn btn-primary" %>
              <%= link_to 'Edit', edit_csv_book_path(@csv, book), class:"btn btn-dark" %>
              <%= link_to 'Delete', csv_book_path(@csv, book), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class:"btn btn-danger" %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% else %>
  <h5 class="mt-4 mb-5 text-danger"><%= description %></h5>
<% end %>

app/views/books/_form.html.erb
<div class="lead">
  <% if @book.errors.any? %>
    <div style="color: red">
      <h1 class="display-6"><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h1>

      <ul>
        <% @book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card shadow mt-4 mb-5">
    <div class="card-body">
      <div class="row mb-3">
        <label for="skill-name" class="col-sm-2 col-form-label">Title</label>
        <div class="col-sm-10">
          <%= form.text_field :title, class: "form-control" %>
        </div>
      </div>

      <div class="row mb-3">
        <label for="skill-name" class="col-sm-2 col-form-label">Author</label>
        <div class="col-sm-10">
          <%= form.text_field :author, class: "form-control" %>
        </div>
      </div>

      <div class="row mb-3">
        <label for="skill-name" class="col-sm-2 col-form-label">Date Published</label>
        <div class="col-sm-10">
          <%= form.datetime_field :date_published, class: "form-control" %>
        </div>
      </div>

      <div class="row mb-3">
        <label for="skill-name" class="col-sm-2 col-form-label">Publisher</label>
        <div class="col-sm-10">
          <%= form.text_field :publisher_name, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/books/edit.html.erb
<h1 class="display-6">Edit Book: <%= @book.title if @book.present? %></h1>

<%= form_with model: @book, url: csv_book_path(@csv, @book) do |form| %>
  <%= render "form", { form: form } %>

  <div class="row d-flex position-sticky bottom-0 bg-white justify-content-center zindex-sticky">
    <div class="col" >
      <div class="d-grid gap-2 d-md-flex justify-content-start">
        <%= form.submit("Save Changes", class: "btn btn-success") %>
        <%= link_to "Show", csv_book_path(@csv, @book), class:"btn btn-primary" %>
        <%= link_to "Back", csv_books_path(@csv), class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/books/index.html.erb
<div id="books">
  <div class="container overflow-hidden">
    <div class="row mt-5">
      <h1 class="display-6">CSV file: <%= @csv.file_name %></h1>
      <div class="lead fw-normal">
        <p class="lead">
          Welcome to the Books Section.
        </p>
        <p class="lead">
          In this section, users can see a list of books uploaded with the above named CSV file. Users then can view,
          edit and delete individual books from the list. <strong>Please, note that the delete action will not be reversed.</strong>
        </p>
      </div>
      <div class="row d-flex zindex-sticky">
        <div class="col" >
          <div class="d-grid py-5 d-md-flex justify-content-start">
            <%= link_to "< Back to upload history", csvs_path, class:"btn btn-secondary" %>
          </div>
        </div>
      </div>
      <div>
        <%= render 'books/books_table', books: @books, description: "No valid entries saved with this csv file. Please review and upload again." %>
      </div>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1 class="display-6">Add New Book</h1>

<%= form_with model: @book, url: csv_books_path(@csv) do |form| %>
  <%= render "form", { form: form } %>

  <div class="row d-flex position-sticky bottom-0 bg-white justify-content-center zindex-sticky">
    <div class="col" >
      <div class="d-grid gap-2 d-md-flex justify-content-start">
        <%= form.submit("Save", class: "btn btn-success") %>
        <%= link_to "Back", csv_books_path(@csv), class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/books/show.html.erb
<h1 class="display-6">Book Details: <%= @book.title if @book.present? %></h1>
<div class="lead">
  <%= render @book %>
  <br>

  <div class="row d-flex position-sticky bottom-0 bg-white justify-content-center zindex-sticky">
    <div class="col" >
      <div class="d-grid gap-2 d-md-flex justify-content-start">
        <%= link_to "Edit", edit_csv_book_path(@csv, @book), class:"btn btn-dark" %>
        <%= link_to 'Delete', csv_book_path(@csv, @book), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class:"btn btn-danger" %>
        <%= link_to "Back", csv_books_path(@csv), class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>